### ISSUE TITLE
build with qpc V7.4.0-rc3 displays undefined references depending on optimization level

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpc#62]
I have a small proof of concept project, which is supposed to build with different tollchains for a TI MSPM0 micro controller running on an ARM Cortex-M0+ core. I can successfully build and run my project with all toolchains (ARM Clang 21.1.1, tiarmclang 5.0.0.STS and arm-none-abi-gcc 14.2.1), when compiling in a Debug configuration (no optimization, max debug symbols => `-gdwarf-4 -O0`). When switching to a release configuration without debug support and size-oriented optimization (`-Os` for gcc, `-Oz` for the Clangs), I experience undefined symbols, when using gcc or ARM Clang. It still builds and runs with tiarmclang. With gcc, I did more checks:
-O0 => builds and runs
-O1 => undefined reference to `'QF_Port_module'`
-O2 (and higher) => undefined reference to `'QF_Port_module'` AND undefined reference to `'Q_onError'`

ARM Clang V21.1 with -Oz complains about undefined references to QF_port_module only. It appears to still see the `Q_onError` symbol.

Seems the optimizer doesn't recognize, that the symbols are referenced from ASM code. GCC optimizer appears to be even more aggresive...

Any ideas, how to fix this?

**Comment by quantum-leaps** [comment]
Hi Stefan,
Thank you for reporting, but I cannot reproduce the issue.

Specifically, I've tried the provided example `qpc\examples\arm-cm\dpp_nucleo-c031c6\qk\gnu`  (example with GNU-ARM), which I've built with the provided Makefile. I've cranked up the optimization for the Release build configuration to `-Os`. Here is a fragment of the build that shows this optimization being used:

```
. . .
C:\qp\qtools/gnu_arm-none-eabi/bin/arm-none-eabi-gcc -c -mcpu=cortex-m0plus   -mthumb -Wall -ffunction-sections -fdata-sections -Os -I../.. -I../../../../../include -I../../../../../ports/arm-cm/qk/gnu -I../../../../../3rd_party/CMSIS/Include -I../../../../../3rd_party/nucleo-c031c6 -DSTM32C031xx  -DNDEBUG ../../../../../ports/arm-cm/qk/gnu/qk_port.c -o rel/qk_port.o

. . .

```
The linking process was successful:

```
C:\qp\qtools/gnu_arm-none-eabi/bin/arm-none-eabi-gcc -Tdpp-qk.ld -mcpu=cortex-m0plus   -mthumb -specs=nosys.specs -specs=nano.specs -Wl,-Map,rel/dpp-qk.map,--cref,--gc-sections  -o rel/dpp-qk.elf rel/bsp.o rel/main.o rel/philo.o rel/table.o rel/system_stm32c0xx.o rel/startup_stm32c031xx.o rel/qep_hsm.o rel/qep_msm.o rel/qf_act.o rel/qf_actq.o rel/qf_defer.o rel/qf_dyn.o rel/qf_mem.o rel/qf_ps.o rel/qf_qact.o rel/qf_qeq.o rel/qf_qmact.o rel/qf_time.o rel/qk.o rel/qk_port.o rel/syscalls.o rel/qstamp.o
C:\qp\qtools/gnu_arm-none-eabi/bin/arm-none-eabi-objcopy -O binary rel/dpp-qk.elf rel/dpp-qk.bin

```

I'm using the newer GCC 15.2.0 (the one bundled in the QP-bundle 8.1.4 for Windows):

```
gcc --version
gcc (MinGW-W64 i686-ucrt-posix-dwarf, built by Brecht Sanders, r6) 15.2.0
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

At this point, I don't have the ARM Clang compiler to try.

Just as you write, I also suspect that the issue is because the missing symbols are used in the inline assembly (in the file `qk_port.c`). However, without reproducing the issue, I cannot devise a workaround.

Please provide some more details and ideally a command-line example with a Makefile that I could run on my machine.

--MMS

**Comment by stefanschober** [comment]
Hi Miro,

thanks for the prompt reply.
I just tried the example you mentioned above and - no surprise - it also builds in my environment. As I'm using a dev container, the build environment is absolutely identical with my own - it uses the exactly same container image. One difference however exists between our builds. As you know, I prefer CMake over Makefiles. My CMake enhancement to qpc always builds qpc as a library, which is then linked to the target. This often enough also collides with the optimizer strategies, if the linker is not aware, that it needs to include another module from the lib. Just now, I have no clue, what could trigger this behavior in the release configurations. In my setup, GCC and CLang share most of the configuration settings. tiarmclang is a little bit different. The general strategy (qpc as a lib) remeins untouched...

Regards
Stefan

**Comment by stefanschober** [comment]
Hi Miro,
I can reproduce the effect with the example you mentioned, by changing the build to the CMake based build, I'm usually using. Please see the screen shots attached. 

<img width="2801" height="1658" alt="Image" src="https://github.com/user-attachments/assets/d2a27fac-70d7-4985-b458-cf5167842c64" />
<img width="2801" height="1658" alt="Image" src="https://github.com/user-attachments/assets/5cd84ec6-e867-4060-800c-e54ec750b092" />

**Comment by quantum-leaps** [comment]
Hi Stefan,
Since [version 8.0.0](https://www.state-machine.com/qpc/history.html#qpc_8_0_0), the QP/C and QP/C++ frameworks are compile-time configurable via the `qp_config.h/hpp` file. This pretty much mandates **building QP from sources** rather than packaging them into a library. In fact, building QP as a library might be *dangerous* as it makes it much more likely to create **broken builds**. Frankly, I stick to the simplest Makefiles (or tool-specific project files, like for ARM-KEIL or IAR-EWARM). Would it be possible to update the CMake infrastructure for building QP from sources?
--MMS

**Comment by stefanschober** [comment]
Hello Miro,

thanks for your reply.
Why do you think, that building QP as a library would increase the risk for broken builds? I can't see that.

The `CMake` infrastructure I added to qpc/qpcpp some time ago already builds `qpc` and `qpcpp` from the sources. I also am not convinced, that the compile-time configuration via a header file like `qp-config.h/hpp` mandates the integration of the compiled object files into the linking stage of the application rather than linking `qpc/qpcpp` into the final app as a library. Such configuration merely demands, that the build system recognizes the changes in the configuration header and re-builds the affected source code files and all subsequent targets. This might then as well be a library. For the app itself, a rebuild of included libs then triggers a new linking step, which rebuilds the app and links in the newly generated libs.
All this is already working like a charm with `CMake`... if not building with `GCC` and release settings for optimization :)
I'm still looking into this nasty effect, to find a proper explanation what's going on. In the meantime, I shall try to enhance the ability of the `CMake` build system in `qpc/qpcpp` to let the user decide, how to build the system. Either as a fully integrated (binary) library or as a set of object files, which are directly integrated into the appliaction's link stage. Allow me some time to fix this...

Best regards
Stefan

**Comment by stefanschober** [comment]
Hi Miro,

It's me again :-D

I just made some checks and now I know the reason, why this happens. As for our target size is of the essence, we are building with aggressive "optimize-for-size" settings. Means, we are also using dead-code/data-elimination via `-flto` used globally. With this, the symbols marked above will be removed. I cannot say at the moment, if this would also happen with the traditional `Makefile` as used in the `qpc/qpcpp` examples.
The solution to this would be to mark the affected symbols with `__attribute__((used))`. E.g. in `qpc/ports/arm-cm/qk/gnu/qk_port.c`:
```
//int32_t volatile QF_int_lock_nest_; // not used
extern char const QF_port_module_[];
__attribute__((used))
char const QF_port_module_[] = "qk_port";
```
This keeps the symbol available under all circumstances. The same obviously would be true for `Q_onError()` in `bsp.c`:
```
__attribute__((used))
void Q_onError(char const * const module, int_t const id)
```

Would it be possible to update qpc/qpcpp with these attributes, to enable max. optimization for size on small targets?
In the small app, I'm doing right now as a proof-of-concept for a larger system, this setting already saves 2kB of Flash memory. The system currently consists of a minimum BSP with only the absolutely necessary functionality to drive a small motor and an AO application with 4 small AOs.

Regards
Stefan

P.S. I'm still planning to do the enhancement of the CMake subsystem as described above...

**Comment by quantum-leaps** [comment]
Hi Stefan,
I've experimented a little with the -flto flag, and here is the [modified qk_port.c file](https://state-machine.com/attachments/qk_port.c) (originally from qpc/ports/arm-cm/qk/gnu/ directory).

I wonder if you could test this file on your end and let me know how it works for you.

If the file works with LTO, it'll be included in the next QP/C/C++ release.

I'm looking forward to hearing from you, so I can finalize the next release.

Thank you,
   Miro

**Comment by stefanschober** [comment]
Hi Miro,

thanks for the quick reply. I can confirm that the build succeeds and the SW runs successfully on the target with your modified `qk_port.c`. See also the attached screenshot from the GCC build. My setup works successfully for all the supported toolchains.

<img width="1364" height="927" alt="Image" src="https://github.com/user-attachments/assets/50e3598c-6b0a-4c57-9246-dc40eb07f410" />

Best regards
Stefan

**Comment by stefanschober** [comment]
Fixed with v9.1.5 - Closed
